// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgforkvofgdxvngaqalj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnZm9ya3ZvZmdkeHZuZ2FxYWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDE3MjMsImV4cCI6MjA2NTM3NzcyM30.BVuknKOqAUqS2vPMf6SJHZVWmz744AydGwYj36f59tY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);