// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pczyevythzyvgtneuvmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjenlldnl0aHp5dmd0bmV1dm1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTY3MDQsImV4cCI6MjA2Mzk5MjcwNH0.AYB7kCUQyt3PTWnn68jKfqFCBjBHE2sHC9vKbTfx-AM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);